services:
  memcached:
    container_name: memcached
    image: memcached:1.6.12
    ports:
      - 11211:11211
    restart: always
  admin:
    container_name: memcached-admin
    image: alphayax/phpmemcachedadmin:latest
    ports:
      - 8081:80
