services:
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - 11211:11211
    restart: always
  admin:
    container_name: memcached-admin
    image: jacksoncage/phpmemcachedadmin:latest
    ports:
      - 8081:80
