version: "2.4"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume:
    name: mongo-volume
