version: "2.4"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass123
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
  mysql_admin:
    container_name: mysql-admin
    image: adminer:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql-volume:
    name: mysql-volume
