version: "2.4"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
    volumes:
      - postgres-volume:/var/lib/postgres/data
  postgres_admin:
    container_name: postgres-admin
    image: adminer:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres-volume:
    name: postgres-volume
