version: "2.4"

services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --requirepass pass123
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis-volume:/data
  redis_admin:
    container_name: redis-admin
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379:0:pass123
    ports:
      - 8081:8081
    restart: always

volumes:
  redis-volume:
    name: redis-volume
